name: "New Idea"
description: "Suggest a new innovation or automation idea"
title: "[IDEA] "
labels: ["idea", "new"]

body:
  - type: markdown
    id: start
    attributes: 
    value: "## Idea Description"   
    
  - type: markdown
    id: description
    attributes:
      value: "Please provide a detailed description of your idea"

  - type: textarea
    id: details
    attributes:
      label: Description
      description: Provide a detailed description of the idea.
      placeholder: Describe your idea here...
      value: ""

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Explain how this idea will benefit the office.
      placeholder: Describe the benefits here...
      value: ""

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this idea.
      options:
        - Low
        - Medium
        - High

  - type: input
    id: name
    attributes:
      label: Submitter Name
      description: Your name.
      placeholder: Your name here...
